$(document).ready(() =>{
    $('.hint-box').click(function(){
      $('.hint').slideToggle(700);
    });
    $('[class*="wrong-answer-"]').click(function(){
      $(this).find('[class*="wrong-text-"]').fadeOut();
      $('.smiley').hide();
      $('.frown').show();
    });
    $('.correct-answer').click(function(){
      $('.frown').hide();
      $('.smiley').show();
      $('[class*="wrong-text-"]').fadeOut();
    });
    $('.reset-box').click(function(){
      $('.frown').hide();
      $('.smiley').hide();
      $('[class*="wrong-text-"]').show();
    })
  });